name: scan
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  adoption:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Adoption script
        uses: adevinta/spark-action-scan-adoption@v0-draft
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # output: 'adoption-report.json'
          verbose: 'true'
          debug: 'true'
          details: 'false'
          sort: 'alphabetical'
          directory: 'packages'
          imports: '@spark-ui'
          datadog-metrics: 'true'
          organisation-name: 'adevinta'

          # configuration: '.spark-ui.cjs'
